version: '3'

dotenv: [ '.env' ]

includes:
    app: ./tasks/app/App.yml
    db: ./tasks/database/PostgresTasks.yml
    migrate: ./tasks/database/MigrationsTasks.yml
    sqlc: ./tasks/database/SqlcTasks.yml

