version: '3'

tasks:
    up:
        cmds:
            - migrate -path internal/db/migration -database $DB_DSN -verbose up

    down:
        cmds:
            - migrate -path internal/db/migration -database $DB_DSN -verbose down

    create:
        cmds:
            - migrate create -ext sql -dir internal/db/migration -seq {{.CLI_ARGS}}

    to:
        cmds:
            - migrate -path internal/db/migration -database $DB_DSN goto {{.CLI_ARGS}}

    force:
        cmds:
            - migrate -path internal/db/migration -database $DB_DSN force {{.CLI_ARGS}}

    drop:
        cmds:
            - migrate -path internal/db/migration -database $DB_DSN drop

    version:
        cmds:
            - migrate -path internal/db/migration -database $DB_DSN version

