version: '3'

tasks:
    up:
        cmds:
            - migrate -path internal/db/migration -database $POSTGRES_DSN -verbose up

    down:
        cmds:
            - migrate -path internal/db/migration -database $POSTGRES_DSN -verbose down
