version: '3'

tasks:
    create:
        cmds:
            -   cmd: podman exec -it postgres-db createdb --username=dharma --owner=dharma simple-bank

    psql:
        cmds:
            -   cmd: podman exec -it postgres-db psql --username=dharma simple-bank

    mock:
        cmds:
            -   mockery --name=Store --with-expecter --recursive --output=./internal/db/mock
        silent: true
