version: '3'

tasks:
    run:
        cmds:
            -   cmd: podman run -d --restart=always --name postgres-db --env-file=.env --publish=5432:5432 docker.io/postgres:15-alpine
                silent: true

    start:
        cmds:
            -   cmd: podman start postgres-db
                silent: true

    stop:
        cmds:
            -   cmd: podman stop postgres-db
                silent: true

    create:
        cmds:
            -   cmd: podman exec -it postgres-db createdb --username=dharma --owner=dharma simple-bank

    drop:
        cmds:
            -   cmd: podman exec -it postgres-db dropdb --username=dharma simple-bank

    psql:
        cmds:
            -   cmd: podman exec -it postgres-db psql --username=dharma simple-bank

    sh:
        cmds:
            -   cmd: podman exec -it postgres-db sh
    mock:
        cmds:
            -   rm -rf vendor
            -   mockgen -package mockdb -destination ./internal/db/mock/store.go github.com/dharmavagabond/simple-bank/internal/db/sqlc Store
            -   go mod vendor
        silent: true
