version: "3"

tasks:
    dev:
        cmds:
            - cmd: gowatch
    deploy:
        cmds:
            - podman build -t simple-bank:prod --target=prod .
            - podman tag simple-bank:prod 904004324775.dkr.ecr.us-east-1.amazonaws.com/simple-bank:latest
            - aws ecr get-login-password --region us-east-1 | podman login --username AWS --password-stdin 904004324775.dkr.ecr.us-east-1.amazonaws.com
            - podman push 904004324775.dkr.ecr.us-east-1.amazonaws.com/simple-bank:latest
    test:
        cmds:
            - cmd: gotestsum -- -count={{.TEST_COUNT | default 0}} ./...
    evans:
        cmds:
            - cmd: evans --host 192.168.64.12 --port 9090 --path proto --proto user.proto,rpc_create_user.proto,rpc_login_user.proto,service_simple_bank.proto,user.proto repl
