version: "3"

tasks:
    proto:
        cmds:
            - rm -f ./pb/*.go
            - rm -f ./doc/swagger/*.swagger.json
            - protoc
              --proto_path=./proto
              --go_out=./internal/pb
              --go_opt=paths=source_relative
              --go-grpc_out=./internal/pb
              --go-grpc_opt=paths=source_relative
              --grpc-gateway_out=./internal/pb
              --grpc-gateway_opt paths=source_relative
              --openapiv2_out=./doc/swagger
              --openapiv2_opt=allow_merge=true,merge_file_name=simple_bank
              proto/*.proto
            - statik -src=./doc/swagger -dest=./doc

    sqlc:
        cmds:
            - sqlc generate
